### ISSUE TITLE
Stall in Field Projector

### ISSUE THREAD

**Issue by cjm721** [CompactMods/CompactMachines#225]
Have several stall reports all in the same chain.

```"Server thread" #24 prio=5
RUNNABLE
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:778)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:797)
	at net.minecraft.world.World.func_175625_s(World.java:2376)
	at org.dave.compactmachines3.tile.TileEntityFieldProjector.getNextProjectorCW(TileEntityFieldProjector.java:108)
	at org.dave.compactmachines3.tile.TileEntityFieldProjector.getMasterProjector(TileEntityFieldProjector.java:119)
	at org.dave.compactmachines3.block.BlockFieldProjector.addProbeInfo(BlockFieldProjector.java:202)
	at org.dave.compactmachines3.compat.TopCompatibility$GetTheOneProbe$1.addProbeInfo(TopCompatibility.java:49)
	at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:143)
	at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:32)
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:108)
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:101)
	at mcjty.theoneprobe.network.PacketGetInfo$Handler$$Lambda$1740/536056848.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
	- locked java.util.ArrayDeque@481a4c90
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by davenonymous** [comment]
This was probably the same as and fixed in #229
