### ISSUE TITLE
[1.12.1] World leaking

### ISSUE THREAD

**Issue by UnPure** [CompactMods/CompactMachines#234]
Hey there.
I currently have the problem that my server is spamming tons of errors in the logs.
The problem is probably related to https://github.com/thraaawn/CompactMachines/issues/233

**latest.log** https://pastebin.com/b5eDRmkP
**fml-junk-earlystartup.log** http://unpure-gaming.de/~minecraft/fml-junk-earlystartup.log

I had to upload the second log to my own server because i dont know about any website that can host files that are 8MB with ~70k lines.

**Forge:** 14.22.0.2475
**CompactMachines:** 3.0.0-b134

Most of the errors are:
Most of the errors are:
Most of the errors are:
1:

    [22:31:44] [Server thread/ERROR]: Failed to save chunk
    java.lang.NullPointerException: null

2:

    [20:28:15] [Server thread/ERROR]: Failed to save chunk
    java.lang.NullPointerException: null
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:334) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:171) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:270) [on.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:206) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

3:

    [22:48:36] [Server thread/DEBUG] [FML]: The world 35e436b (unpure) may have leaked: seen 2045 times.

Removing CompactMachines stops the spam.
I'm not sure but i think this is related to https://github.com/thraaawn/CompactMachines/issues/233 because the world has a worldborder (5000 in every direction) and one of the machines is outside of that border (~5100 on X).

**Comment by davenonymous** [comment]
After fiddling with your server files for a bit I'm actually not sure anymore that CM3 is the one causing the spam. I'd need to reproduce this issue in a deobfuscated environment, which I was not able to do after a few hours with this.

Not sure what to do here, I'd need a more concise testcase that reliably triggers the error and can be setup in a dev environment. Not sure how achievable that is with the ~140 mods and 4gb world of yours.

**Comment by DeadSix27** [comment]
@UnPure Do you run any of these versions?:
```
CodeChickenLib-1.10.2-2.5.9.283-universal.jar
ChickenChunks-1.10.2-2.2.0.52-universal.jar
CodeChickenCore-1.10.2-2.4.1.102-universal.jar
```
EDIT: Nvm 1.12, but On 1.10 I run into leak issues with those versions too.

I thought it's cm2 too first since I narrowed it down to chicken's stuff and cm2.. but turns out even without cm2 it leaks..

**Comment by UnPure** [comment]
I do have CodeChickenLib (3.1.2.297) in the pack.

**Comment by DeadSix27** [comment]
@UnPure Ye I tested it myself in 1.12 as I reported the issue to ChickenChunks tracker.. but I can't reproduce it on 1.12 (in the little testing I did that is)

**Comment by robotgryphon** [comment]
Closing this as stale and not reproduceable.
