### ISSUE TITLE
Server Crash when entering machine ( And then failure to restart server )

### ISSUE THREAD

**Issue by FSDel** [CompactMods/CompactMachines#253]
Steps to Reproduce:
1. Create a Normal Compact Machine
2. Attempt to enter the machine

Expected Result:
The player enters the machine

Actual Result:
The server crashes, and can not be restarted.

Reproducability - 2 / 5

Crash text:
`[10:25:30] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at org.dave.compactmachines3.world.tools.SpawnTools.spawnEntitiesInMachine(SpawnTools.java:59) ~[SpawnTools.class:?]
        at org.dave.compactmachines3.tile.TileEntityMachine.func_73660_a(TileEntityMachine.java:147) ~[TileEntityMachine.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1829) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
        ... 4 more
[10:25:30] [Server thread/ERROR]: This crash report has been saved to: C:\ATLauncher\Servers\DNSTechpack_12001\.\crash-reports\crash-2017-11-12_10.25.30-server.txt
[10:25:30] [Server thread/INFO]: Stopping server`

[crash-2017-11-12_10.25.30-server.txt](https://github.com/thraaawn/CompactMachines/files/1464227/crash-2017-11-12_10.25.30-server.txt)

**Comment by davenonymous** [comment]
This is probably already fixed in d3b1b8694a6996282c3976acc9856561aca5c2e4
I'll probably put a new release out later today.

**Comment by davenonymous** [comment]
Could you retest this with the latest build 165 from curse, please?

**Comment by FSDel** [comment]
Issue has not reproduced after 10 attempts.

Thanks for the prompt fix!
