### ISSUE TITLE
Crash: NullReferenceException in TileEntityRedstoneTunnel

### ISSUE THREAD

**Issue by rezonant** [CompactMods/CompactMachines#303]
**Compact Machines version**: 3.0.4
**Forge version**: 14.23.1.2582
**I am not using Optifine**: No Optifine
**Link to Crashlog**: https://pastebin.com/Kmz87bPJ

**Description of the problem including expected versus actual behavior:**
Client crashes consistently after placing a Sky Resources casing & combustion heater directly on to a Redstone tunnel. Redstone tunnel was on the bottom of the compact machine, and was configured to North. Server continues to run, but no clients can connect without causing a client-side crash.

The stack trace:

```
java.lang.NullPointerException: Ticking block entity
	at org.dave.compactmachines3.tile.TileEntityRedstoneTunnel.getRedstonePowerInput(TileEntityRedstoneTunnel.java:20)
	at org.dave.compactmachines3.block.BlockRedstoneTunnel.func_180656_a(BlockRedstoneTunnel.java:144)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:388)
	at net.minecraft.world.World.func_175651_c(World.java:3249)
	at com.bartz24.skyresources.base.tile.TileBase.getRedstoneSignal(TileBase.java:44)
	at com.bartz24.skyresources.base.tile.TileBase.receivedPulse(TileBase.java:29)
	at com.bartz24.skyresources.technology.item.ItemCombustionHeater.update(ItemCombustionHeater.java:184)
	at com.bartz24.skyresources.base.tile.TileCasing.func_73660_a(TileCasing.java:69)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Upon examining the code at the crash site:

```
        DimensionBlockPos dimpos = WorldSavedDataMachines.INSTANCE.machinePositions.get(coords);
```

it must be either that `WorldSavedDataMachines.INSTANCE` is null (seems unlikely since the game crashed the first time immediately upon placing the block, not after restarting the client), or `WorldSavedDataMachines.INSTANCE.machinePositions` is null...

**Steps to reproduce:**

I haven't reproduced this in an isolated world (yet) but am booting up IDEA to see if I can get some more information. This should be sufficient:

1. Make a compact machine and get into it
2. Place a redstone tunnel on the floor
3. Place a SkyResources combustion heater on it.
4. Game should crash.

**Comment by davenonymous** [comment]
This should have been fixed in 3.0.5
Did you try the latest version of the mod?
