### ISSUE TITLE
Game crash when looking inside - Better With Mods edition

### ISSUE THREAD

**Issue by ThaDaVos** [CompactMods/CompactMachines#309]
**Read then remove this section**:
If you are reporting a bug regarding the interior view of the Machines, the one you get when you right click a machine, do not report it to any other mod author involved in the crash. It is highly likely that its CM3s fault.

It's because of the above - seems the same as here: https://github.com/thraaawn/CompactMachines/issues/289

Game crashes when right clicking a compact machine to look inside when there is BWM (Better with Mods) axles and gearboxes inside (haven't tested with other blocks)

See (full log: https://gist.github.com/dvdbot/382a510ab58060ad5b7f35912ccbf237) :

I think the following is the cause:
> Time: 3/3/18 5:27 PM
Description: Rendering screen
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to betterwithmods.common.blocks.mechanical.BlockAxle
	at betterwithmods.common.blocks.mechanical.tile.TileAxle.getDirections(TileAxle.java:198)
	at betterwithengineering.ie.MechPower$AxleRF.tick(MechPower.java:257)
	at betterwithmods.common.blocks.mechanical.tile.TileAxle.lambda$update$0(TileAxle.java:252)
	at betterwithmods.common.blocks.mechanical.tile.TileAxle$$Lambda$2904/1944208155.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at betterwithmods.common.blocks.mechanical.tile.TileAxle.func_73660_a(TileAxle.java:252)
	at org.dave.compactmachines3.gui.machine.GuiMachine.renderTileEntities(GuiMachine.java:284)
	at org.dave.compactmachines3.gui.machine.GuiMachine.renderChunk(GuiMachine.java:199)
	at org.dave.compactmachines3.gui.machine.GuiMachine.func_73863_a(GuiMachine.java:98)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Compact Machines version**: Latest
**Forge version**: 14.23.2.2618
**I am not using Optifine**: true
**Link to Crashlog**: [here](https://gist.github.com/dvdbot/382a510ab58060ad5b7f35912ccbf237)
**Screenshot (if possible)**: [here](https://pasteboard.co/Hadg2WQ.png) [here2](https://pasteboard.co/HadgAfX.png)

**Description of the problem including expected versus actual behavior:**
You should be able to just see inside without crashing

**Steps to reproduce:** right click to view inside a compact machine which has Better With Mods stuff in it - at least axles

**Comment by davenonymous** [comment]
Thanks for the report! I will look into it soon.

**Comment by davenonymous** [comment]
I have plans on reworking how the internal rendering is done, but it might be a while before I get around to implement that. Sorry for the inconvenience.
