### ISSUE TITLE
Cant use compact machines of a certain id

### ISSUE THREAD

**Issue by chaosprinz** [CompactMods/CompactMachines#316]
Playing on 'Enigmatica2-Expert'
compact-machines-version: 3.0.7-b197
forge: 14.23.2.2645
Not using optifine

latest.log : https://gist.github.com/chaosprin76/2ab1694e775084e4bc3d9e7b3ccac9bc
screenshot: https://imgur.com/a/HhIEd

I built 2 small compact machines, set stuff up in there and they work like a charm.
I built a third one with maximum size. As i try to enter it, it just shows up the Minecraft-user-interface, but nothing more and i cant do anything.
I tried it with other sizes but with the same result. I just cant enter Machine with ID 2.

I tried to reproduce in a creative world, with the same result, but on Machine-id 3.

**Comment by davenonymous** [comment]
I can not reproduce this. I have more than 10 machines in my test world and all of them work fine.
Any more ideas on how to reproduce this?

**Comment by davenonymous** [comment]
Look like we're getting [stuck in a loop](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/structures/WorldGenSirenIsland.java#L23) in the Ice and Fire mod.

This is running over and over again:
```
"Server thread" #86 prio=5 os_prio=0 tid=0x0000000068357800 nid=0x1d20 runnable [0x000000008f1ae000]
   java.lang.Thread.State: RUNNABLE
        at net.minecraft.world.World.func_180501_a(World.java:319)
        at com.github.alexthe666.iceandfire.structures.WorldGenSirenIsland.func_180709_b(WorldGenSirenIsland.java:28)
        at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:72)
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by chaosprinz** [comment]
Sorry for the late response. I did try to reproduce with Compact Machines alone without success, as you did too. I took a look into the Ice&Fire-config. At least, there is an option to disable these siren-islands. 
Will try it.
