### ISSUE TITLE
Cannot view manual/move into machines without creative mode (Modern Skyblock 3 pack).

### ISSUE THREAD

**Issue by ManIkWeet** [CompactMods/CompactMachines#355]
**Compact Machines version**: compactmachines3-1.12.2-3.0.12-b215
**Forge version**: forge-1.12.2-14.23.4.2749-universal
**I am not using Optifine**: It never improves performance, a big hoax.
**Link to Crashlog**: There's no crash
**Screenshot (if possible)**: Hard to screenshot a right-click

**Description of the problem including expected versus actual behavior:**
When rightclicking the PSD anywhere, no manual shows.
When rightclicking the PSD onto a machine block, two dimension travels happen, one to go in, the next instantly to go out.
Both those behaviours don't happen in Creative mode (/gamemode 1)
Opping player has no effect.

**Steps to reproduce:**
Install the Modern Skyblock 3 pack locally (allocate at least 6GB of ram...).
Download and run the Modern Skyblock 3 server locally (allocate at least 3GB of ram...)
Log into server, run commands (op yourself on server):
/island create 1
/give yourname dirt 1
/give yourname sapling 1
Rightclick quest book (should be in inventory), select "Kitchensink Mode" and claim the quest reward (this unlocks everything)
/give yourname compactmachines3:psd
/give yourname compactmachines3:machine
Go into machine using PSD.
Observe a loading screen and then appearing right back in dimension 0.

Quite a few steps, I haven't tried a standalone version of CS3 on a server yet, I wouldn't be shocked if it's a mod-conflict somehow.

Still doesn't explain why the only way to get it working is creative mode...

**Comment by Khepricus** [comment]
I'm experiencing the same issue with Modern Skyblock 3 (same details as above) but it seems important to note that:
1. The issue only appears in multiplayer servers. In single player the compact machines can be entered in both survival and creative modes
2. When I tested using Forge 1.12.2-14.23.4.2759 and no mods other than Compact Machines 1.12.2-3.0.12-b215 compact machines could be entered in both multiplayer and single player regardless of game mode

Unfortunately the server log from Modern Skyblock 3 isn't particularly helpful (the error shown happens when moving between any dimensions and is reported in TeamJM/journeymap#42. Removing JourneyMap does not resolve the issue):
<details><summary>Log Snippet</summary><p>

```
[08:07:09] [Server thread/INFO] [FML]: Loading dimension 144 (world) (net.minecraft.server.dedicated.DedicatedServer@7c4311b7)
[08:07:09] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world 144
[08:07:09] [Server thread/INFO] [compactmachines3]: Loading saved data for machine world
[08:07:09] [Server thread/INFO] [compactmachines3]:  > 2 spawn points
[08:07:09] [Server thread/INFO] [compactmachines3]:  > Next machine id: 2
[08:07:09] [Server thread/INFO] [compactmachines3]:  > Players with beds in CM dimension: 0
[08:07:09] [Thread-202/INFO] [THAUMCRAFT]: Starting aura thread for dim 144
[08:07:11] [Server thread/INFO] [journeymap]: <PlayerName> joining dimension 144
[08:07:11] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type journeymap.common.network.DimensionPermissionPacket in channel jm_dim_permission
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
	at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2223_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:721) [pl.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:623) [pl.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:610) [pl.class:?]
	at org.dave.compactmachines3.world.tools.TeleportationTools.teleportPlayerToMachine(TeleportationTools.java:46) [TeleportationTools.class:?]
	at org.dave.compactmachines3.world.tools.TeleportationTools.teleportPlayerToMachine(TeleportationTools.java:176) [TeleportationTools.class:?]
	at org.dave.compactmachines3.block.BlockMachine.func_180639_a(BlockMachine.java:340) [BlockMachine.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type journeymap.common.network.DimensionPermissionPacket in channel jm_dim_permission
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
	... 35 more
[08:07:11] [Server thread/INFO] [journeymap]: <PlayerName> joining dimension 0
[08:07:11] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type journeymap.common.network.DimensionPermissionPacket in channel jm_dim_permission
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
	at journeymap.common.network.PacketHandler.sendDimensionPacketToPlayer(PacketHandler.java:60) [PacketHandler.class:1.12.2-5.5.2]
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:68) [ForgeEvents.class:1.12.2-5.5.2]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2223_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1205) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:721) [pl.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:623) [pl.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:610) [pl.class:?]
	at org.dave.compactmachines3.world.tools.TeleportationTools.teleportPlayerOutOfMachineDimension(TeleportationTools.java:100) [TeleportationTools.class:?]
	at org.dave.compactmachines3.world.tools.TeleportationTools.teleportPlayerOutOfMachine(TeleportationTools.java:198) [TeleportationTools.class:?]
	at org.dave.compactmachines3.item.ItemPersonalShrinkingDevice.func_77659_a(ItemPersonalShrinkingDevice.java:83) [ItemPersonalShrinkingDevice.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) [aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:763) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) [mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type journeymap.common.network.DimensionPermissionPacket in channel jm_dim_permission
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
	... 36 more
```
</p></details>

**Comment by ManIkWeet** [comment]
It narrowed it down a bit, removing "TinkerStages-1.12.2-2.0.15.jar" (and commenting the related lines in "stages.zs") makes the PSD and teleporation work again...

**Comment by cyberemissary** [comment]
I ran into the same issue, anyone has any ideas how to make this work on a server without removing any mods? (and without creative mode)

**Comment by PhoenixMage** [comment]
I think this is more a TinkerStages issue then a Compact Machines one. It has the same effect on the Immersive Engineering Engineer's Manual.

@ManIkWeet I am going to steal your reproduction steps to log this with TinkerStages, hope you dont mind.

**Comment by ManIkWeet** [comment]
@PhoenixMage I am not too sure about it being Tinker Stages, as other people with this issue couldn't resolve it by removing said mod... It only seems to work for me...

**Comment by PhoenixMage** [comment]
@ManIkWeet Where did you find others with the issue? Removing Tinker Stages fixed similar issues I had with both this and IE.

**Comment by ManIkWeet** [comment]
@PhoenixMage this pack has a discord channel, I found others there :) https://discord.gg/3yHZvHk
