### ISSUE TITLE
Exception being thrown when preview of a machine tries to render water

### ISSUE THREAD

**Issue by urikkiru** [CompactMods/CompactMachines#377]
**Compact Machines version**:
compactmachines3-1.12.2-3.0.14-b247.jar
**Forge version**:
14.23.5.2781
**I am not using Optifine**:

**Description of the problem including expected versus actual behavior:**

When the compact machine contains water, it throws an exception when previewing the contents of the block. The preview renders without showing any water.

**Steps to reproduce:**
Place water in a compact machine. Exit the machine. Preview the machine in the machine GUI.

There is no crash log, just this in the latest.log file:

`[21:40:30] [Client thread/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:2, y:41, z:2
  Block Class:   class net.minecraft.block.BlockStaticLiquid
  Registry Name: minecraft:water
  Metadata:      0
  State:         minecraft:water[level=0]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98) [CustomBlockDispatcher.class:?]
	at org.dave.compactmachines3.gui.machine.GuiMachine.renderLayer(GuiMachine.java:558) [GuiMachine.class:?]
	at org.dave.compactmachines3.gui.machine.GuiMachine.func_73863_a(GuiMachine.java:148) [GuiMachine.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldProvider.getBiomeForCoords(WorldProvider.java:429) ~[aym.class:?]
	at net.minecraft.world.World.func_180494_b(World.java:149) ~[amu.class:?]
	at net.minecraft.world.biome.BiomeColorHelper.func_180285_a(SourceFile:36) ~[anj.class:?]
	at net.minecraft.world.biome.BiomeColorHelper.func_180288_c(SourceFile:55) ~[anj.class:?]
	at net.minecraft.client.renderer.color.BlockColors$6.func_186720_a(BlockColors.java:107) ~[bik$9.class:?]
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185) ~[bik.class:?]
	at net.minecraft.client.renderer.BlockFluidRenderer.func_178270_a(BlockFluidRenderer.java:48) ~[bvn.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:84) ~[bvm.class:?]
	... 23 more
[21:40:32] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] CCL Caught an exception rendering a block. See the log for info.`

**Comment by davenonymous** [comment]
Oops. That's a lot of spam. On it. Hotfix will be released shortly.

**Comment by davenonymous** [comment]
Should be fixed in 5554176.

**Comment by davenonymous** [comment]
I'll release version 3.0.15 in a minute, might take a moment to appear on curse.
Thanks for the report!
