### ISSUE TITLE
client locked out of server

### ISSUE THREAD

**Issue by DarkShadow012** [CompactMods/CompactMachines#573]
### I am not using performance mods.

- [X] Confirm

### Description

I play on my server with other 2 people on TNP Limitless 6 Modpack.
I created a compact machine enter it and when i started to put cables from refined storage to connect the machines from mekanism and refined storage, the server kicked me out and can't go back in.
the server is giving me an error that the player could not be place on the world, with invalid data and i called twice at the server.

### Mod Version

5.1.0

### Forge Version

1.19.2 43.2.21

### Link to Crashlog

https://gist.github.com/DarkShadow012/4ff669cdd2edb2503302e595932e7c85

### How to reproduce

dont think i can reproduce

**Comment by robotgryphon** [comment]
This appears to be a Refined Storage bug, per the debug log:
```
java.lang.ClassCastException: class com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode cannot be cast to class com.refinedmods.refinedstorage.apiimpl.network.node.CableNetworkNode (com.refinedmods.refinedstorage.apiimpl.network.node.ImporterNetworkNode and com.refinedmods.refinedstorage.apiimpl.network.node.CableNetworkNode are in module refinedstorage@1.11.6 of loader 'TRANSFORMER' @656672fb)
	at com.refinedmods.refinedstorage.blockentity.CableBlockEntity.writeUpdate(CableBlockEntity.java:47) ~[refinedstorage-1.11.6.jar%231062!/:1.11.6]
	at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.m_5995_(BaseBlockEntity.java:35) ~[refinedstorage-1.11.6.jar%231062!/:1.11.6]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:152) ~[server-1.19.2-20220805.130853-srg.jar%231215!/:?]
```
